spring:
  application:
    name: chat
  datasource:
    url: ${CHAT_DB_URL:jdbc:postgresql://localhost:5432/chat_db}
    username: ${CHAT_DB_USERNAME:postgres}
    password: ${CHAT_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8080
