spring:
  application:
    name: auth
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${AUTH_DB_USERNAME:postgres}
    password: ${AUTH_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: ${LIQUIBASE_LOG_LEVEL:DEBUG}
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_BINDER_LOG_LEVEL:TRACE}

server:
  port: 8080
