spring:
  application:
    name: auth

server:
  port: 8081

jwt:
  secretKey: ${JWT_SECRET_KEY}

app:
  security:
    public-paths:
      - /api/auth/register
      - /api/auth/login
      - /api/auth/refresh
      - /actuator/health
